// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAj0kcyBOdFmzv-4cGvS6ZYZK7r-F6u9HY',
    appId: '1:340883128619:web:9f635cba0f7b5afbfbc56e',
    messagingSenderId: '340883128619',
    projectId: 'woman-needs-app',
    authDomain: 'woman-needs-app.firebaseapp.com',
    storageBucket: 'woman-needs-app.appspot.com',
    measurementId: 'G-VTXQ080RCD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCf17gek1-o5mDxCnYpclgdyeg6gaJ4ER0',
    appId: '1:340883128619:android:0fafbc63821fafadfbc56e',
    messagingSenderId: '340883128619',
    projectId: 'woman-needs-app',
    storageBucket: 'woman-needs-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVXIXUvX-hsbiU4859QHT3rb3QoUMfgJs',
    appId: '1:340883128619:ios:fd5be1ba93c5d4a8fbc56e',
    messagingSenderId: '340883128619',
    projectId: 'woman-needs-app',
    storageBucket: 'woman-needs-app.appspot.com',
    androidClientId: '340883128619-v2jauo3sub73n62hbsl2tudveapgj19u.apps.googleusercontent.com',
    iosClientId: '340883128619-d7e7t3glcu26rg1usstd3iuo7gfepejp.apps.googleusercontent.com',
    iosBundleId: 'com.example.womanNeedsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDVXIXUvX-hsbiU4859QHT3rb3QoUMfgJs',
    appId: '1:340883128619:ios:d006afe563c21694fbc56e',
    messagingSenderId: '340883128619',
    projectId: 'woman-needs-app',
    storageBucket: 'woman-needs-app.appspot.com',
    androidClientId: '340883128619-v2jauo3sub73n62hbsl2tudveapgj19u.apps.googleusercontent.com',
    iosClientId: '340883128619-kijngsl0bnbvtj4k8lhsv4qdardvcv91.apps.googleusercontent.com',
    iosBundleId: 'com.example.womanNeedsApp.RunnerTests',
  );
}
